apiVersion: v1
kind: Service
metadata:
  name: backend-deployment-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django-backend
  type: NodePort
status:
  loadBalancer: {}
