# Generated by Django 4.1.7 on 2023-05-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0002_add_is_active_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
