# Generated by Django 4.1.7 on 2023-05-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
