# Generated by Django 4.1.7 on 2023-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0006_remove_product_image_product_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
