# Generated by Django 4.1.7 on 2023-04-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0006_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
