# Generated by Django 4.1.7 on 2023-04-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0007_checkout_payment_method_checkout_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_ecommerce_api.order'),
        ),
    ]
