# Generated by Django 4.1.7 on 2023-05-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0007_category_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=50),
        ),
    ]
