# Generated by Django 4.1.7 on 2023-04-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0008_checkout_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_ecommerce_api.order'),
        ),
    ]
