# Generated by Django 4.1.7 on 2023-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0009_alter_checkout_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(default='Credit Card', max_length=50),
        ),
    ]
