# Generated by Django 4.1.7 on 2023-05-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0013_alter_user_options_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
