# Generated by Django 4.1.7 on 2023-05-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_api', '0014_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
