name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push MarketX-backend image
      uses: docker/build-push-action@v2
      with:
        context: MarketX-backend
        file: MarketX-backend/Dockerfile
        push: true
        tags: mohamedsorour/marketx-backend:latest

    - name: Build and push MarketX-frontend image
      uses: docker/build-push-action@v2
      with:
        context: MarketX-frontend/ecommerce_angular_project
        file: MarketX-frontend/ecommerce_angular_project/Dockerfile
        push: true
        tags: mohamedsorour/marketx-frontend:latest
