name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Google Cloud SDK
    #   uses: google-github-actions/setup-gcloud@v0.3.0
    #   with:
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true

    # - name: Set up kubectl
    #   run: |
    #     gcloud components install kubectl
    #     gcloud container clusters get-credentials marketx --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push MarketX-backend image
      uses: docker/build-push-action@v2
      with:
        context: MarketX-backend
        file: MarketX-backend/Dockerfile
        push: true
        tags: mohamedsorour/marketx-backend:latest

    - name: Build and push MarketX-frontend image
      uses: docker/build-push-action@v2
      with:
        context: MarketX-frontend/ecommerce_angular_project
        file: MarketX-frontend/ecommerce_angular_project/Dockerfile
        push: true
        tags: mohamedsorour/marketx-frontend:latest

    # - name: Update MarketX-backend deployment on GKE
    #   run: |
    #     kubectl delete  deployment backend-deployment 
    #     kubectl apply -f https://raw.githubusercontent.com/mohamedsorour1998/MarketX/master/MarketX-backend/backend-deployment.yaml


    # - name: Update MarketX-frontend deployment on GKE
    #   run: |
    #     kubectl delete  deployment frontend-deployment 
    #     kubectl apply -f https://raw.githubusercontent.com/mohamedsorour1998/MarketX/master/MarketX-frontend/frontend-deployment.yaml
